### ISSUE TITLE
Squirtle paralyzed at virdian forest

### ISSUE THREAD

**Issue by Marcin1503** [kylecoburn/PokeBot#18]
Seed: 1428925057
Bot: 1.4.1

I was attacked by pikachu. I cannot escape and pikachu attacked with thunder wave. Bot get into loop trying use antidote on paralyzed squirtle.
Please add reseting if squirtle is paralyzed.

**Comment by kylecoburn** [comment]
Thank you, nice find! Right now it doesn't distinguish the poison status change from paralysis, which is what causes this to happen.

**Comment by kylecoburn** [comment]
Finally got around to verifying this. Fixed by 9d05ee343efa2a96eb7bf98e1eee7361bf4bb55d.
