### ISSUE TITLE
Paint also caught pokemons

### ISSUE THREAD

**Issue by Marcin1503** [kylecoburn/PokeBot#19]
I added by myself that code:
```
local xPokemon = 125
	local yPokemon = 15
	drawText(xPokemon,yPokemon,"Pokemons: ")
	local squirtx = Pokemon.indexOf("squirtle")
	if squirtx ~= -1 then
		drawText(xPokemon,yPokemon +5,"Squirtle")
	end
	
	
	local pidgeyx = Pokemon.indexOf("pidgey")
	if pidgeyx ~= -1 then
		drawText(xPokemon,yPokemon+15,"Pidgey")
	end
	
	local spearowx = Pokemon.indexOf("spearow")
	if spearowx ~= -1 then
		drawText(xPokemon,yPokemon+15,"Spearow")
	end
	
	local parasx = Pokemon.indexOf("paras")
	if parasx ~= -1 then
		drawText(xPokemon,yPokemon+20,"Paras")
	end
	
	local oddishx = Pokemon.indexOf("oddish")
	if oddishx ~= -1 then
		drawText(xPokemon,yPokemon+20,"Oddish")
	end
	
	local nidx = Pokemon.indexOf("nidoran", "nidorino", "nidoking")
	if nidx ~= -1 then
		local att = Pokemon.index(nidx, "attack")
		local def = Pokemon.index(nidx, "defense")
		local spd = Pokemon.index(nidx, "speed")
		local scl = Pokemon.index(nidx, "special")
		drawText(60, 0,"Nido stats: "..att.." "..def.." "..spd.." "..scl)
	end
	nidx = Pokemon.indexOf("nidoran")
	if nidx == -1 then
		nidx = Pokemon.indexOf("nidorino")
		if nidx == -1 then
			nidx = Pokemon.indexOf("nidoking")
			if nidx ~= -1 then
				drawText(xPokemon,yPokemon+10,"Nidoking")
			end
		else
			drawText(xPokemon,yPokemon+10,"Nidorino")
		end
	else
		drawText(xPokemon,yPokemon+10,"Nidoran")
	end
```

**Comment by mathiasbynens** [comment]
In the stream, the Java bridge (#3) takes care of it. There are no plans to open-source it, sadly.

**Comment by Marcin1503** [comment]
I will write my own bridge ;) I see that , your java bridge is just connecting to local server on some port. I can recreate it in C# ;)

**Comment by Marcin1503** [comment]
![image](https://cloud.githubusercontent.com/assets/11877723/7115166/ca0bf6e4-e1e5-11e4-81d0-c4000870eecc.png)

**Comment by wreck3d** [comment]
I would LOVE if you could tell me how to get this to show for my Pokemon Yellow bot. @Marcin1503 
![aaa20db6-e1e5-11e4-838c-a151d9adfb72](https://cloud.githubusercontent.com/assets/10440098/7671905/669d3052-fcaf-11e4-8245-89d2067914f9.png)

**Comment by Marcin1503** [comment]
Lua has possibility to connect to tcp ip server. @kylecoburn have application written in java, after catching pokemon pokebot send information to this server, then server updates the screen. This application (bridge) is not open source. If you want similar functionality you have to write your own bridge system.

**Comment by wreck3d** [comment]
The amount of crazy work/code for simple images :P 
Interesting...
Would you plan on trying to create one? I'd use it...lol.
Like, I don't even know where to think of starting for all this coding.

**Comment by wreck3d** [comment]
@Marcin1503 Did you ever wind up writing your own bridge?
If so, can I PLEASE use it? Very important & I just cannot figure it out :/
