### ISSUE TITLE
Just for fun add "Dont check nidoran stats"

### ISSUE THREAD

**Issue by Marcin1503** [kylecoburn/PokeBot#20]
Right now I just commented line with stats checking and replacing it with always be false (or true, I don't remember condition).

I had a few good runs with with very bad nido. I can add this flag by myself but every time when you update bot, I have to add this.

**Comment by mathiasbynens** [comment]
@Marcin1503 

> I can add this flag by myself but every time when you update bot, I have to add this.

Submit a patch, like so: #21. :)
