### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by mathiasbynens** [kylecoburn/PokeBot#28]
_Moved from https://github.com/kylecoburn/PokeBot/commit/0fd1258ca17f7d74edbac72fa0afc2b5c6d58bb3#comments:_

Tagging would make it easier to replay runs against an older version of the bot. I.e. to revert to v1.3.0 of the code, you could then just enter: `git checkout tags/v1.3.0`. (Currently, you have to look for the commit hash manually and go from there.)

If you want to make this happen, run the following commands:

```sh
git tag v1.4.3 bf648ec1fae9277d82187a18ec3654076a768d0e
git tag v1.4.2 e3782505bcb6c82e074d6d0831c0987b1201ddfd
git tag v1.4.1 b8f99f649082002e48dd06897713eda1df9d6c34
git tag v1.4.0 0fd1258ca17f7d74edbac72fa0afc2b5c6d58bb3
git tag v1.3.0 db58061e9edab5255c64cb54f1101c3d6b447615
git push --tags
```

And from then on, after committing a new version, just run `git tag vX.Y.Z` and `git push --tags` after `git push`.

----

We should also update https://github.com/kylecoburn/PokeBot#run-the-bot-locally — after cloning the repository, the latest tag should be checked out. If someone were to download the repository in its current state (i.e. @ 11233437e1fc72c6283ceed259bf9a2dc85b3dae) they wouldn’t get v1.4.2 (although the version number in the code would say so) but [v1.4.2 with some code changes](https://github.com/kylecoburn/PokeBot/compare/e3782505bcb6c82e074d6d0831c0987b1201ddfd...11233437e1fc72c6283ceed259bf9a2dc85b3dae). This might lead to seeds that don’t reproduce against the proper version.

**Comment by kylecoburn** [comment]
Done and merged with changelog, thanks.

**Comment by mathiasbynens** [comment]
:+1:
