### ISSUE TITLE
Freeze in menu

### ISSUE THREAD

**Issue by Marcin1503** [kylecoburn/PokeBot#29]
Seed: 4

I don't describe because it is in virdian forest and you can quickly check it by yourself

**Comment by kylecoburn** [comment]
Thanks, could not reproduce in 1.4.3. Please let me know if you see it after the update.

**Comment by Marcin1503** [comment]
In 1.4.3 seed 4 resets before virdian forest because of different routing or strategy. You can debug 1.4.2 on seed 4, find the issue in code and then update 1.4.3 code with this fix
