### ISSUE TITLE
Java bridge

### ISSUE THREAD

**Issue by mathiasbynens** [kylecoburn/PokeBot#3]
The Java bridge (that is used to communicate with LiveSplit among other things) doesn’t seem to be part of the repository. Can this be added?

**Comment by kylecoburn** [comment]
It's not something we plan on supporting, sorry. The Java bridge is part of the stream itself, not the bot.

**Comment by mathiasbynens** [comment]
Fair enough. The LiveSplit integration (+ splits, see #2) is the only thing I really miss when locally running the bot in search of a good seed anyway.

**Comment by kylecoburn** [comment]
LS integration is part of the Java bridge, so for our purposes they are the same thing.

**Comment by mathiasbynens** [comment]
I know :) Understood.
