### ISSUE TITLE
Freeze in menu 1429085932

### ISSUE THREAD

**Issue by Marcin1503** [kylecoburn/PokeBot#31]
Freeze in menu at silph Rival. Bot try to use bicycle in fight.

**Comment by kylecoburn** [comment]
Appreciate the report. It's actually trying to use the item at index -1 (i.e. the item doesn't exist). I haven't seen this specific issue, but some changes in 1.4.3 _should_ prevent it from getting stuck like this. Please report back if you see it again, thanks!
