### ISSUE TITLE
Freeze in menu

### ISSUE THREAD

**Issue by Marcin1503** [kylecoburn/PokeBot#32]
Seed:1429133489

Bot try to use pokeball on nugget bridge (nidoking has already 23 level and there is no rarecandy in inventory)

**Comment by mathiasbynens** [comment]
Same with seed `924639`.

**Comment by kylecoburn** [comment]
Thanks for the report. There are some ongoing improvements to teaching Thrash. This is fixed for v1.4.4.

**Comment by kylecoburn** [comment]
Fixed by d123cabe757d2583c0991b4a9ea344e93d005528 and fef346823ac04bb06bc811cca9105ccd0583cf6d.
