### ISSUE TITLE
Twitch Chat ♂ as "Mars"

### ISSUE THREAD

**Issue by phase** [kylecoburn/PokeBot#33]
In the Twitch Chat, PokeBot prints "♂" as "Mars" (found by people wanting to name Nidoran as "♂").

**Comment by PsiLupan** [comment]
Not a bug, AFAIK. It's due to a lack of Unicode support.

**Comment by phase** [comment]
Is there any way we can give it unicode support?

**Comment by kylecoburn** [comment]
This should be working now. Thanks for the suggestion.
