### ISSUE TITLE
Infinite loop fighting Koga's Muk

### ISSUE THREAD

**Issue by theroflcoptr** [kylecoburn/PokeBot#37]
Seed 1429739267, Version 1.4.4
Bot uses X-Accuracy, Muk disables Horn Drill, bot gets stuck trying to use Horn Drill

**Comment by kylecoburn** [comment]
Interesting, thanks. Will take a look.

**Comment by kylecoburn** [comment]
This is fixed by 82dfaaa3a552b1936a425b3112fa519da7b5c868. I'm still not sure why it would get stuck trying to use horn drill - this is the same disabled check used throughout the run - but this fixes attempting to set up on Muk when hp is too low to survive a tackle from Koffing.
