### ISSUE TITLE
Oak and Old Man Encounters Causing Increment

### ISSUE THREAD

**Issue by PsiLupan** [kylecoburn/PokeBot#41]
Given that these are scripted, I don't think they should count for the total encounters.

0xD05A in Red/Blue, 0xD059 in Yellow for Gameboy Emulators that aren't BizHawk.
0x105A / 0x1059 in WRAM for BizHawk.

00 is a usual battle
01 is the pre-scripted OLD MAN battl
02 is a safari zone battle
03  obligates you to run away. (unused) 
04 is a pre-scripted OAK battle, which (temporarily) causes the enemy Pokemon to cry PIKAAA, and which always catches the target Pokemon. The target Pokemon is erased after the battle.
05+ are glitch states in which you are sort of the Pokemon.

Check the flag and don't increment encounter if 04 for Oak or 01 for Old Man. 

Sources:
http://aurellem.org/vba-clojure/html/rom.html for flag data.
http://datacrystal.romhacking.net/wiki/Pok%C3%A9mon_Red/Blue:RAM_map

**Comment by kylecoburn** [comment]
This is known, but has always been near the bottom of my priorities (cf. counting Snorlax and Marowak). There's certainly a case that these could all be changed, but it is not the precedent that these new ones in Yellow wouldn't count, so I haven't bothered with it.
