### ISSUE TITLE
Reset in wrong moment

### ISSUE THREAD

**Issue by Marcin1503** [kylecoburn/PokeBot#43]
Pokemon yellow
2.0.1
Nidoran was caught with third pokeball. Then in virdian forest bot tried to catch pidgey and failed. Bot should reset in this moment. Right now bot continues run, beat brock, go to the grass near mt.moon and then resets because of too low pokeballs.

**Comment by kylecoburn** [comment]
Interesting, thanks. This should be fixed in 2.0.2.
