### ISSUE TITLE
Broken Twitch Chat Emotes

### ISSUE THREAD

**Issue by PsiLupan** [kylecoburn/PokeBot#44]
https://github.com/kylecoburn/PokeBot/blob/master/ai/strategies.lua#L1126

Because the line appends a "." to the end, it breaks the "BibleThump" and "Kappa"

Also, there was an instance of it saying, "KreyGasm" when the emote is "Kreygasm", but I've not hunted that one down.

**Comment by kylecoburn** [comment]
Thanks, this is worked around in 2.0.2. I'll probably end up adding the punctuation into the reset messages themselves later.
