### ISSUE TITLE
Display Party Pokémon like TPP 

### ISSUE THREAD

**Issue by wreck3d** [kylecoburn/PokeBot#47]

**Comment by wreck3d** [comment]
What exactly do I do in order to make my party pokemon update live to my stream? I just need the Pokemon's sprite, name, level, and gender symbol would be cool.
Thanks!

**Comment by PsiLupan** [comment]
You'd need a UI created with a programming language of your choice, a TCP/UDP server, and a TCP/UDP client written with LuaSockets to notify of Pokemon in your party.

**Comment by wreck3d** [comment]
How much do you think it'd cost me to have someone make this?
