### ISSUE TITLE
Easy, Quick Question

### ISSUE THREAD

**Issue by wreck3d** [kylecoburn/PokeBot#48]
When the bot completes a run, what happens?
Does it automatically start again?
Does it stay at the hall of fame screen?

Because I'm letting it run over night and I don't wanna miss a great run/possible "WR."

**Comment by mathiasbynens** [comment]
It just keeps on running, just like the live stream. Check your screenshots folder or read the log if you don’t wanna miss any completed runs.

**Comment by wreck3d** [comment]
Thanks!
