### ISSUE TITLE
Freeze/Memory?

### ISSUE THREAD

**Issue by wreck3d** [kylecoburn/PokeBot#53]
First time this has happened.
Yellow Version.
Encountered a female Nidoran and I looked over & noticed the bot stopped.
![err](https://cloud.githubusercontent.com/assets/10440098/7735878/13514ad0-ff0e-11e4-8e4c-a3f7222a0f37.png)

**Comment by kylecoburn** [comment]
This is a duplicate of #30. Please search past issues before posting, thanks.
