### ISSUE TITLE
Request #2

### ISSUE THREAD

**Issue by wreck3d** [kylecoburn/PokeBot#55]
my second request is:

After it levels the Nidoran to level 8 (when it checks its stats), have it check them with the start menu after that battle in Viridian Forest. Way more human, obviously, and yeah, that'd be more "humanly as possible."

**Comment by RenaKunisaki** [comment]
Real speedrunners do in fact check them upon level up, so no reason the bot can't do this too. Even if they're only displayed for a few frames, with practice people are able to read them well enough to tell good stats from bad. Just watch werster for example.

**Comment by kylecoburn** [comment]
There are some ways stat checking could be improved, but there's no reason for this - stats are already displayed when you level up. A human runner might revisit the menu to reshow them, but that's just a waste of time to the bot.

**Comment by wreck3d** [comment]
The reason would be to make it more human-like.

**Comment by kylecoburn** [comment]
Please see the previous two comments, it would do nothing to make it more humanlike.
