### ISSUE TITLE
Making it work with the New Bizhawk - Found how to

### ISSUE THREAD

**Issue by bouletmarc** [kylecoburn/PokeBot#56]
if you remove "client.reboot_core()" from main.lua (line 106) it will make it work with all news bizhark version, I found out that he was keeping rebooting in a loop and lead to a emulator crash. Removing this line will make it work, nothing else.

**Comment by bouletmarc** [comment]
maybe this reboot its probably needed to "reload" emulator values, I guess, if news bizhawk still need this reboot I suggest Placing it before the "while true loop" so he will perform the reboot he need before reading the main loop.

**Comment by RenaKunisaki** [comment]
#40 mentions fixing the reboot loop by letting it run for a frame or two first.

**Comment by mathiasbynens** [comment]
@bouletmarc or @RenaKunisaki Would you mind submitting a pull request that adds recent BizHawk compatibility?
