### ISSUE TITLE
Infinite loop in menu

### ISSUE THREAD

**Issue by Venalyo** [kylecoburn/PokeBot#8]
With the version 1.3, the seed number 491329568 loop in inventory menu just before the fight with the Bug Catcher, after Nidoran grass.

**Comment by mathiasbynens** [comment]
Confirmed.

**Comment by kylecoburn** [comment]
Thanks for the report. This is fixed in 1.4 which should finally be pushed tomorrow.

**Comment by KriPet** [comment]
Same problem with 1428589128, presumably this is also fixed?

**Comment by kylecoburn** [comment]
Now fixed in 1.4.
